# Generated by Django 4.1.13 on 2025-01-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='artists/%Y/%m/%d')),
                ('bio', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='song_thumbnails/%Y/%m/%d')),
                ('song', models.FileField(upload_to='songs/%Y/%m/%d')),
                ('size', models.IntegerField(default=0)),
                ('playtime', models.CharField(default='0:00', max_length=15)),
                ('featured', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('artists', models.ManyToManyField(related_name='songs', to='music.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='music_genre_name_de76de_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['id', 'slug'], name='music_artis_id_4048f9_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name'], name='music_artis_name_e97718_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['id', 'slug'], name='music_song_id_578821_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['name'], name='music_song_name_d45546_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-created'], name='music_song_created_3dd9a4_idx'),
        ),
    ]
